site_name: Model de Dades de la Infraestructura Tramviaria
nav:
    - Home: index.md
    - Obra Civil:
      - 01 Domini Public: Domini_public.md
      - 02 Traçat: Tracat.md
      - 03 Parades: Parades.md
      - 04 Pavimentació: Pavimentacio.md
      - 05 Reg: Reg.md
      - 06 Drenatge: Drenatge.md
      - 07 Enllumenat: Enllumenat.md
    - Sistemes Tramviaris:
      - 08 Catenària: Catenaria.md
      - 09 Multitubular: Multitubular.md
      - 10 Energia: Energia.md
      - 11 Subestacions: Subestacions.md
      - 12 SAE: SAE.md
      - 13 Senyalització ferroviària: Senyalitzacio_ferroviaria.md
      - 14 Semaforització: Semaforitzacio.md
      - 15 Senyalització viària: Senyalitzacio_viaria.md
      - 16 Videovigilància: Videovigilancia.md
      - 17 Tallers i Cotxeres: Tallers_i_cotxeres.md
    - Sistemes Auxiliars:
      - 18 Mobiliari urbà: Mobiliari_urba.md
      - 19 Estructures complementàries: Estructures_complementaries.md
theme:
    name: null
    custom_dir: 'cinder'
